before_script:
  - wget -N http://buildboost.org/build.xml
  
jdk:
  - openjdk6
#fail  - oraclejdk7
#fail  - oraclejdk6
  
language: java
script: "ant -DrootRepository='git:https://github.com/FunThomas424242/ant-ube-task.git'"